name: Unit test
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: subosito/flutter-action@v2.8.0
      - run: flutter test